<div class="row">
	<div class="col-lg-12">
		<div class="page-header">
			<h1 id="forms">Join &laquo;GftHint&raquo; Today.</h1>
			<p class="gft-statement text-muted">
				You don't know what presents to give your friends? Join us now and see what they really want!
			</p>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-lg-5 col-md-5">
		<div class="well">
			<form class="form" action="">
				<fieldset>
					<legend>Sing Up</legend>
					<div class="form-group">
						<label>Email</label>
						<input type="text" class="form-control"  placeholder="Email">
					</div>
					<div class="form-group">
						<label>Password</label>
						<input type="text" class="form-control"  placeholder="Password">
					</div>
					<div class="form-group">
						<label>Confirm password</label>
						<input type="text" class="form-control"  placeholder="Confirm Password">
					</div>
					<hr/>

					<div class="form-group">
						<label>First name</label>
						<input type="text" class="form-control"  placeholder="First Name">
					</div>

					<div class="form-group">
						<label>Last Name</label>
						<input type="text" class="form-control"  placeholder="Last Name">
					</div>

					<div class="form-group">
						<label>Birthday</label>
						<div class="gft-dob-group">
							<select class="form-control">
								<option value="">Day</option>
							</select><select class="form-control">
								<option value="">Month</option>
							</select><select class="form-control">
								<option value="">Year</option>
							</select>
						</div>
					</div>

					<div class="form-group">
						<label>Photo</label>
						<input type="file" />
					</div>
				</fieldset>
				<br/>
				<div class="form-group text-left">
					<button type="submit" class="btn btn-primary">Sing up</button>
				</div>
			</form>
		</div>
	</div>
</div>
<div class="row">
	<hr/>
</div>