<script src="<?=$this->basePath('/js/jquery.min.js')?>"></script>
<script src="<?=$this->basePath('/js/angular.min.js')?>"></script>
<script src="<?=$this->basePath('/js/underscore-min.js')?>"></script>
<script src="<?=$this->basePath('/js/bootstrap.min.js')?>"></script>
<script src="<?=$this->basePath('/js/angular-file-upload-shim.min.js')?>"></script>
<script src="<?=$this->basePath('/js/angular-file-upload.min.js')?>"></script>
<script src="<?=$this->basePath('/js/app.js')?>"></script>