<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="description" content="" />
<meta name="author" content="" />

<title>&laquo;GftHint&raquo;</title>

<link href="<?=$this->basePath('/css/bootstrap.min.css')?>" rel="stylesheet">
<link href="<?=$this->basePath('/css/font-awesome.min.css')?>" rel="stylesheet">
<link href="<?=$this->basePath('/css/style.css')?>" rel="stylesheet">

<!--[if lt IE 9]>
<script src="<?=$this->basePath('/js/html5shiv.js')?>"></script>
<script src="<?=$this->basePath('/js/respond.min.js')?>"></script>
<![endif]-->
